### ISSUE TITLE
Support for CustomTriggers

### ISSUE THREAD

**Issue by danielmarbach** [Particular/NServiceBus.AzureFunctions.Worker.ServiceBus#221]
Currently, custom triggers are not supported. Some customers are using them and would like to have better support for custom triggers.

[Discussion group entry](https://discuss.particular.net/t/why-custom-trigger-definitions-not-supported-for-isolated-worker/2999)

**Comment by udidahan** [comment]
I noticed that there wasn't a follow-up posted to the discussion group about this.
