### ISSUE TITLE
Dynamic endpoint name via configuration

### ISSUE THREAD

**Issue by johnkors** [Particular/NServiceBus.AzureFunctions.Worker.ServiceBus#28]
We currently want to set the endpoint name dynamically (i.e. appending environment name (dev/test/prod) or machinename for local dev). This does not work well with the source generator and attributes. Is there a way of dynamically setting the endpoint name? Earlier we could use `%mykey%` which would point to a variable from `local.settings.json`.

Moved to #29 :~We already use some other configuration key for the ASB connection string. Even if I use the `                    endpointConfig.Transport.ConnectionString(connectionString);` API, it fails to start. Is some feature hard coded to the `AzureWebJobsServiceBus` key? If so, why? Feels odd to not be able to decide key here, or if I have set it using the API mentioned previously, it should honor that.~

**Comment by timbussmann** [comment]
Hey @johnkors , thanks for your inputs

> Is there a way of dynamically setting the endpoint name?

Currently, the recommended usage is to use the source generator but you can create your own trigger definition instead which is a bit noisier and technically not "officially supported" as we focused the 1.0 release on the auto-generated trigger, but essentially what you can do is to define an ASB trigger like this:

```
public class FunctionEndpointTrigger
{
    IFunctionEndpoint endpoint;

        public FunctionEndpointTrigger(IFunctionEndpoint endpoint)
        {
            this.endpoint = endpoint;
        }


        [Function("<TriggerName>")]
        public async Task Run(
            [ServiceBusTrigger("<EndpointName>")] byte[] messageBody,
            IDictionary<string, string> userProperties,
            string messageId,
            int deliveryCount,
            string replyTo,
            string correlationId,
            FunctionContext context)
        {
            await endpoint.Process(messageBody, userProperties, messageId, deliveryCount, replyTo, correlationId, context);
        }
};
```

Your endpoint name also needs to be configured for the `UseNServiceBus` API, which you can do in two ways:
* Use the `UseNServiceBus` overload that accepts an endpoint name string 
* Specify an `ENDPOINT_NAME` environment variable (or in `IConfiguration`)

Either way, the endpoint name used needs to match the queue name on the `ServiceBusTrigger`.

>  Is some feature hard coded to the AzureWebJobsServiceBus key? If so, why? 

They connection needs to match the same connection string used by the generated ServiceBus trigger and the current API doesn't support changing this key without a manual trigger, so it expects this connection string to be available when using a Service Bus trigger. When using the custom trigger definition as shown above, you should be able to configure the connection string used by the Azure Service Bus trigger. You then need to configure the same value for `endpointConfig.Transport.ConnectionString(connectionString);`. As you see, the custom trigger approach currently requires a bit of duplicate configuration.

Is there a reason you don't want to use the default key name for the Azure Service Bus trigger?

Please let me know if that workaround helps.

**Comment by johnkors** [comment]
>Is there a reason you don't want to use the default key name for the Azure Service Bus trigger?

Because I already a configuration with the value in all environments— just with another key. So it's basically just a bit more hassle to migrate, since I would have to update settings in all environments, and all devs would also have to update because you hardcoded it to something. Seems unnecessary, that's all. I rarely come across client libraries that sets a requirement on config keys, so found that to be a minor nag during testing. Not a big issue, just annoying :)

**Comment by timbussmann** [comment]
I've raised this as a separate feature request here: https://github.com/Particular/NServiceBus.AzureFunctions.Worker.ServiceBus/issues/29 (to decouple this a bit from the topic of endpoint name configuration) to be improved on a future version. 

Have you been able to test whether the suggested workaround removes the current limits?

**Comment by timbussmann** [comment]
btw. another workaround idea that I haven't tested: you could also assign the required `AzureWebJobsServiceBus` key from your custom environment variable to `IConfiguration` as part of the host builder setup, e.g.

                .ConfigureAppConfiguration((context, builder) =>
                {
                    context.Configuration["AzureWebJobsServiceBus"] = Environment.GetEnvironmentVariable("MyCustomKey");
                })`

**Comment by johnkors** [comment]
After reviewing what's generated, I see that you [just pipe it to the ASB trigger](https://github.com/Particular/NServiceBus.AzureFunctions.Worker.ServiceBus/blob/main/src/NServiceBus.AzureFunctions.Worker.SourceGenerator/TriggerFunctionGenerator.cs#L113). And _that_ supports dynamic endpoint names.

```csharp
[assembly: NServiceBusTriggerFunction("%ENDPOINT_NAME%")]
```

So if not completely dynamic (code), at least we can do what we need via configuration.

**Comment by johnkors** [comment]
Just a sidenote on that. 

If we use the host builder method `.UseNServiceBus(c => ..)` _without_ specifying a endpoint name, it looks for the `ENDPOINT_NAME` from config. In that case, it would also make sense for the `NServiceBusTriggerFunction` to do the same for parity, which would simplify it to : 

```csharp
[assembly: NServiceBusTriggerFunction]
```

Not sure if that is doable with the source generators approach, though?

**Comment by timbussmann** [comment]
> Not sure if that is doable with the source generators approach, though?

yeah unfortunately not, as the code is generated at build time which, depending on your deployment approach can be anywhere and not have access to the required environment variables. That's why at the moment is is recommended to specify the endpoint name via the `NServiceBusTriggerFunction` and use the `UseNServiceBus` that doesn't require an endpoint name as it will find the name from the attribute.

**Comment by johnkors** [comment]
Are there any known issues when deploying this to Azure? I get this working with the azure function tools locally, but when deploying to azure I cannot see the functions that are auto-generated.

**Comment by timbussmann** [comment]
> Are there any known issues when deploying this to Azure?

we tested this successfully with deployments to azure.

From your warning it looks like the code generator is not able to run on your github action. Can you share your GHA definition or do you have a working repro sample for us to look at?

**Comment by johnkors** [comment]
https://github.com/fplbot/fplbot/runs/3544210281?check_suite_focus=true

**Comment by johnkors** [comment]
Agh, seems like it was an issue using the .NET 5 5.0.100 SDK. Bumping it to 5.0.400 removed the silent error. 🤷‍♂️. No idea why.

**Comment by johnkors** [comment]
I'll close this before my ramblings go further on to other topics, and I'll open a sep tickets for other issues.

**Comment by timbussmann** [comment]
> Agh, seems like it was an issue using the .NET 5 5.0.100 SDK. Bumping it to 5.0.400 removed the silent error. 🤷‍♂️. No idea why.

Glad to hear that you were able to solve it. It seems there are some strict version dependencies for the source generator. I'll raise a dedicated feature request focused on surfacing these source generator issues more visibly to start with 👍 Thanks for the feedback!
