### ISSUE TITLE
Source generator loading failures not showing up as errors

### ISSUE THREAD

**Issue by timbussmann** [Particular/NServiceBus.AzureFunctions.Worker.ServiceBus#32]
Failures to load the `TriggerFunctionGenerator ` due to issues with loading `Microsoft.CodeAnalysis` only show up as warnings and do not prevent the project/solution from building. This can lead to cases where no trigger is being generated while this isn't noticed by the user. Once deployed, no trigger is found and messages are not picked up from the queue.

e.g. see this issue about loading failures https://github.com/Particular/NServiceBus.AzureFunctions.Worker.ServiceBus/issues/26 that are not automatically surfacing if not explicitly enabled.

As mentioned on the linked issue, using `<WarningsAsErrors>CS8032</WarningsAsErrors>` can help to surface this.

**Comment by kbaley** [comment]
This was fixed with #190. Documentation update: https://github.com/Particular/docs.particular.net/pull/5881

This will be included when version 4.1.0 is released.
