### ISSUE TITLE
Log potential concurrency mismatch as a warning

### ISSUE THREAD

**Issue by SeanFeldman** [Particular/NServiceBus.AzureFunctions.Worker.ServiceBus#338]
#### Is your improvement related to a problem? Please describe.

https://discuss.particular.net/t/limit-parallel-processing-of-messages/3635

#### Describe the suggested solution

[Log a warning ](https://github.com/Particular/NServiceBus.AzureFunctions.Worker.ServiceBus/blob/b1a1f6d70371f296eb76996083e9dc9c0dc96373/src/NServiceBus.AzureFunctions.Worker.ServiceBus/Serverless/TransportWrapper/PipelineInvoker.cs#L18) about the potential mismatch between the concurrency setting via NServiceBus and Azure Functions for scenarios where the user is seeking serial processing by setting `LimitMessageProcessingConcurrencyTo` to 1.

**Comment by SeanFeldman** [comment]
👍 for Roslyn analyzers as that's very much aligned with Azure Functions SDK approach as well.

**Comment by dvdstelt** [comment]
This was fixed with https://github.com/Particular/NServiceBus.AzureFunctions.Worker.ServiceBus/issues/302
