### ISSUE TITLE
New AzureServiceBusTransport Constructor Not Setting Fully Qualified Namespace when Injecting an IFunctionEndpoint

### ISSUE THREAD

**Issue by sanfordn** [Particular/NServiceBus.AzureFunctions.Worker.ServiceBus#369]
#### Description
Within the UseNServiceBus() configuration section, we are using the "newer" constructor for building an AzureServiceBusTransport with a DefaultAzureCredential token. We followed the [steps in the documentation for moving from Version 2 to Version 3](https://docs.particular.net/transports/upgrades/asbs-2to3#configuration-options-tokencredential) as it was specifically called out how we can specify a DefaultAzureCredential as the TokenCredential. 

It seems to build the EndpointConfiguration just fine when inside of our startup file, but once we get to our Sender, it puts the Fully qualified service bus name into the ConnectionString property of the IFunctionEndpoint implementation.
#### Expected behavior
When using the [constructor where you can specify a fully qualified namespace](https://github.com/Particular/NServiceBus.Transport.AzureServiceBus/blob/7c8565fd35f51d07ace2a0f3d93add2e94136884/src/Transport/AzureServiceBusTransport.cs#L36), the FullyQualifiedNamespace hosts whatever value is passed into it throughout the lifetime of the service. 
#### Actual behavior
Once we get into the Sender, the FullyQualifiedNamespace variable is empty in the EndpointConfiguration, and we get an error after we do a RouteToThisEndpoint() and IFunctionEndpoint.Send() saying 
`The value '' is not a well-formed Service Bus fully qualified namespace. (Parameter 'fullyQualifiedNamespace`. And the FullyQualifiedNamespace value that we passed in the Startup is inside the ConnectionString property
#### Versions
NServiceBus.AzureFunctions.Worker.ServiceBus 4.1.0
Please list the version of the relevant packages or applications in which the bug exists.        

### Steps to reproduce

Configure NServicebus with settings like this

```csharp
.UseNServiceBus(ServiceBusQueueName, serviceBusNameSpaceFQDN, configuration =>
                {
                    var endpointConfiguration = configuration.AdvancedConfiguration;
                    
                    var credential = new DefaultAzureCredential();
                    var transportWithTokenCredential = new AzureServiceBusTransport(serviceBusNameSpaceFQDN, credential);
                    endpointConfiguration.UseTransport(transportWithTokenCredential);
                })
```

### Relevant log output

```shell
The value '' is not a well-formed Service Bus fully qualified namespace. (Parameter 'fullyQualifiedNamespace`. And the FullyQualifiedNamespace value that we passed in the Startup is inside the ConnectionString property
```

**Comment by DavidBoike** [comment]
Hey @sanfordn,

When using Azure Functions, I don't believe you get to directly instantiate the transport yourself due to how the triggers work. Note the [known constraints and limitations](https://docs.particular.net/nservicebus/hosting/azure-functions-service-bus/isolated-worker#custom-triggers-known-constraints-and-limitations) section of the docs, how it says calling `AdvancedConfiguration.UseTransport()` is not supported…as the `AdvancedConfiguration` is an `EndpointConfiguration` I would assume that applies inside the `.UseNServiceBus(…)` method as well.

Is it possible to do what you're trying to do using the `Transport` property as the docs suggest?

**Comment by sanfordn** [comment]
Previously in NServiceBus.AzureFunctions.Worker.ServiceBus v4.0.0-rc.2, we were able to do this:
(where configuration is the `ServiceBusTriggeredEndpointConfiguration` from within `UseNServiceBus()`)
```csharp
configuration.Transport.TokenCredential = new DefaultAzureCredential();
```

But it doesn't look like anything like that is available anymore.

![image](https://github.com/Particular/NServiceBus.AzureFunctions.Worker.ServiceBus/assets/43021738/7da830b1-5b4f-40b5-9288-b744383513b0)

**Comment by DavidBoike** [comment]
@sanfordn I've done a bit of digging and it just appears as though this package isn't set up to support managed identity yet.

There's already an issue https://github.com/Particular/NServiceBus.AzureFunctions.Worker.ServiceBus/issues/368 raised to support that as a feature.

Given that the [known constraints of calling UseTransport() are not supported](https://docs.particular.net/nservicebus/hosting/azure-functions-service-bus/isolated-worker#custom-triggers-known-constraints-and-limitations) this isn't really a bug, it's a currently unsupported feature.

I would encourage you to follow https://github.com/Particular/NServiceBus.AzureFunctions.Worker.ServiceBus/issues/368 for udpates. We regularly do enhancements on our Azure-related packages so I'll suggest that as a for the next iteration.

**Comment by sanfordn** [comment]
Thanks for taking a look, I'll keep my eye on it!
