### ISSUE TITLE
Use the ServiceBusReceivedMessage SDK type for generated trigger

### ISSUE THREAD

**Issue by SeanFeldman** [Particular/NServiceBus.AzureFunctions.Worker.ServiceBus#402]
### Describe the suggested improvement

SDK type `ServiceBusReceivedMessage` is now supported and could be used for the trigger and NSB implementation.

https://github.com/Particular/NServiceBus.AzureFunctions.Worker.ServiceBus/blob/17a7aff2740a481df9f8f0d7dd018b0c5b9e34d3/src/NServiceBus.AzureFunctions.Worker.Analyzer/TriggerFunctionGenerator.cs#L110-L115

**Comment by dvdstelt** [comment]
Thanks for reporting this @SeanFeldman. I've added it as a recommendation so it can be picked up.

**Comment by SeanFeldman** [comment]
`ServiceBusMessageActions` is also available for message disposition operations.

**Comment by andreasohlund** [comment]
This will be shipped in 5.1.0
