### ISSUE TITLE
.NET 8

### ISSUE THREAD

**Issue by johnkors** [Particular/NServiceBus.AzureFunctions.Worker.ServiceBus#415]
### Describe the bug

Trying out porting to .NET 8, I don't seem to get the source generator to work. The trigger is never found. 

Adding a manual trigger works as manual workaround.

Should this package work with .NET 8 or only from a specific version and up? 

### Steps to reproduce

.NET 8 host, 4.2.1 package version.

#### Workarounds
Create the trigger manually instead of relying on source generators.

**Comment by bording** [comment]
@johnkors I did some quick testing, and I'm not able to reproduce the problem you're describing. I have an Azure Functions project that is targeting .NET 8, and I'm seeing the generator properly creating the `FunctionEndpointTrigger` class.

Can you share some more specific steps, or even better, a sample project that demonstrates the problem?

**Comment by SeanFeldman** [comment]
@johnkors, what version of the Azure Functions Core Tools are you using?

**Comment by johnkors** [comment]
> Can you share some more specific steps, or even better, a sample project that demonstrates the problem?

It's open source [here](https://github.com/fplbot/fplbot/tree/3f12e48b8df8dd2512e14a4fa5f63e2457a902c8/src/FplBot.Functions)




> @johnkors, what version of the Azure Functions Core Tools are you using?

```
$ func --version
4.0.5455
``` 

Looks like [the latest one](https://github.com/Azure/azure-functions-core-tools/releases)

**Comment by SeanFeldman** [comment]
There were a few issues with the latest release of the Worker SDK. Wondering if it's related. If you downgrade `Microsoft.Azure.Functions.Worker.Sdk` off v16, will it work again?

**Comment by bording** [comment]
@johnkors I cloned your repo and made the following changes to FplBot.Functions.csproj on the `main` branch:

- Updated the TFM to `net8.0`
- Updated the Microsoft.Azure.Functions packages to the latest versions

That resulted in the following project file:

```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <AzureFunctionsVersion>v4</AzureFunctionsVersion>
    <OutputType>Exe</OutputType>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <WarningsAsErrors>CS8032</WarningsAsErrors>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Http" Version="3.1.0" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Sdk" Version="1.16.2" OutputItemType="Analyzer" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker" Version="1.20.0" />
    <PackageReference Include="NServiceBus.AzureFunctions.Worker.ServiceBus" Version="2.0.2" />
    <PackageReference Include="Slackbot.Net.SlackClients.Http" Version="$(SlackbotNetVersion)" />
  </ItemGroup>
  <ItemGroup>
    <None Update="host.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="local.settings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>Never</CopyToPublishDirectory>
    </None>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\FplBot.Messaging.Contracts\FplBot.Messaging.Contracts.csproj" />
  </ItemGroup>
</Project>
```
When I build that project, the resulting `net8.0` assembly has the `FunctionEndpointTrigger` in it, just like the `net6.0` assembly.

The generator seems to be working fine. I'm not seeing any differences between the `net6.0` assembly I built and the `net8.0` assembly.

**Comment by johnkors** [comment]
Odd. When I run that exact csproj with 2.0.2 (or 4.2.1), the func tooling only gets me the web trigger - but not the NServicebus source-generated one.

<img width="662" alt="snip 9FBh1lKw@2x" src="https://github.com/Particular/NServiceBus.AzureFunctions.Worker.ServiceBus/assets/206726/e0fadd30-60bd-4050-b088-0ca2c5493a82">

**Comment by johnkors** [comment]
Looks like @SeanFeldman was on to something:

```diff
     <PackageReference Include="Microsoft.Azure.Functions.Worker.Sdk" Version="1.16.2" OutputItemType="Analyzer" />
-    <PackageReference Include="Microsoft.Azure.Functions.Worker" Version="1.20.0" />
+    <PackageReference Include="Microsoft.Azure.Functions.Worker" Version="1.16.0" />
```

Matching the SDK with the worker minor versions, and I get it as expected:

![snip zTAkbUwz@2x](https://github.com/Particular/NServiceBus.AzureFunctions.Worker.ServiceBus/assets/206726/18c77690-2261-44e1-9f77-f9a21cb6a5d5)

**Comment by johnkors** [comment]
Did some quick testing, and it seems like the issue starts with `<PackageReference Include="Microsoft.Azure.Functions.Worker" Version="1.19.0" />`. 16, 17, 18 works.

**Comment by SeanFeldman** [comment]
Trust @SeanFeldman 😉

**Comment by johnkors** [comment]
Not great that @bording got it to work with 20, and I didn't though. 🤷 

At least this unblocks me a bit, so thanks – both of you.

I reported [a different silent failure to generate the trigger](https://github.com/Particular/docs.particular.net/pull/5495) some 2 years ago, but I think that was caused by something else. This felt very similar, in that my context was the same. The project did a major .NET SDK upgrade, STS to LTS etc. Not sure if you can do anything to warn this time around? Using strict dependency version range (higher upper bound) is probably not a favourable solution..?

**Comment by bording** [comment]
@johnkors To be clear, I didn't run your function, I just compiled it and verified that the source generator worked correctly and added the `FunctionEndpointTrigger` class as it was supposed to. I can confirm that there was nothing wrong with our source generator, which is what you claimed when you opened this issue.

If changing the versions of the Worker packages fixed the issue, then that means that you were hitting some other unrelated bug in that version of the package, as @SeanFeldman pointed out in https://github.com/Particular/NServiceBus.AzureFunctions.Worker.ServiceBus/issues/415#issuecomment-1821678456

If you upload a copy of the function assembly that isn't working for you to this issue, I'd be happy to take a look at it and verify that the source generator is working as intended.

**Comment by johnkors** [comment]
Yeah, I've no quarrels or interest in any blame game (NServiceBus vs Microsoft). Just wanted to report something not working. There's at least something uncompatible or non-working somewhere, and I didn't have any issues if didn't use the source generated trigger. Adding the trigger manually without any source-gen involved worked perfectly fine. For me, success is `func` picks it up, while you stop at "source generated" in a dll. I think we just view what success is from different angles.

Semantics, but it's up to you how you want to treat that information (document it, link to this ticket etc, ignore it). 

Closing.

**Comment by bording** [comment]
> Yeah, I've no quarrels or interest in any blame game (NServiceBus vs Microsoft)

@johnkors It definitely wasn't my intention to make seem like I was trying to move blame or anything like that. My intention was pointing out that if the source generator itself wasn't the source of the problem, then it's not in my power to fix the issue if the problematic code wasn't in this repo.

Digging into this a bit more, it looks like the problem you've run into is https://github.com/Azure/azure-functions-dotnet-worker/issues/2065

It looks like Microsoft introduced a breaking change that is causing the way we are generating the function trigger to not work. 

We are monitoring that issue, and if Microsoft ends up deciding not to fix the break they introduced, we'll be sure to update our source generator and release new packages.

**Comment by SeanFeldman** [comment]
> Microsoft introduced a breaking change

Several, to be exact.

**Comment by johnkors** [comment]
> then it's not in my power to fix the issue if the problematic code wasn't in this repo.

Sure, I understand the root cause is not possible to fix. A proposal for actionable things that would help you + clients of the source generator package:

- Create a sticky issue in this repo: 

> "Warning! Breaking changes in the Worker SDK. This package is currently incompatible with versions x-y (see ticket 1337). WIP to add support for breaking changes is tracked <here>". 

- And/or document it at [particular.net](https://docs.particular.net/samples/azure-functions/service-bus-worker/)

Just some thoughts, as that would have saved hours of digging/debugging. I'm probably not alone in doing .NET 8 migration bits atm 👍

**Comment by bording** [comment]
FYI we have released patches that should make improve the behavior between our package and the latest versions of the functions packages. See #428 for details.
